"""empty message

Revision ID: 976a9328ee26
Revises: 9be5b0234170
Create Date: 2026-02-11 17:30:38.223875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976a9328ee26'
down_revision = '9be5b0234170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_post_timestamped'))
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('timestamped')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamped', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.create_index(batch_op.f('ix_post_timestamped'), ['timestamped'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
